package com.foodbot.food;

import java.util.Map;
import java.util.TreeMap;

public final class IngredientIcons {
    private static final String DEFAULT_ICON = "";
    private static final Map<String, String> ICONS = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);

    static {
        ICONS.put("egg", "🥚");
        ICONS.put("eggs", "🥚");
        ICONS.put("تخم مرغ", "🥚");
        ICONS.put("potato", "🥔");
        ICONS.put("potatoes", "🥔");
        ICONS.put("سیب زمینی", "🥔");
        ICONS.put("rice", "🍚");
        ICONS.put("برنج", "🍚");
        ICONS.put("tuna", "🐟");
        ICONS.put("fish", "🐟");
        ICONS.put("ماهی تن", "🐟");
        ICONS.put("تن ماهی", "🐟");
        ICONS.put("ماهی", "🐟");
        ICONS.put("beef", "🥩");
        ICONS.put("meat", "🥩");
        ICONS.put("گوشت", "🥩");
        ICONS.put("chicken", "🍗");
        ICONS.put("مرغ", "🍗");
        ICONS.put("onion", "🧅");
        ICONS.put("پیاز", "🧅");
        ICONS.put("garlic", "🧄");
        ICONS.put("سیر", "🧄");
        ICONS.put("tomato", "🍅");
        ICONS.put("tomatoes", "🍅");
        ICONS.put("گوجه فرنگی", "🍅");
        ICONS.put("گوجه", "🍅");
        ICONS.put("cheese", "🧀");
        ICONS.put("پنیر", "🧀");
        ICONS.put("milk", "🥛");
        ICONS.put("شیر", "🥛");
        ICONS.put("bread", "🍞");
        ICONS.put("نان", "🍞");
        ICONS.put("shrimp", "🦐");
        ICONS.put("pepper", "🌶️");
        ICONS.put("salt", "🧂");
        ICONS.put("spice", "🧂");
        ICONS.put("spices", "🧂");
        ICONS.put("ادویه", "🧂");
        ICONS.put("sugar", "🍬");
        ICONS.put("شکر", "🍬");
        ICONS.put("butter", "🧈");
        ICONS.put("oil", "🫒");
        ICONS.put("lemon", "🍋");
        ICONS.put("لیمو", "🍋");
        ICONS.put("lettuce", "🥬");
        ICONS.put("cucumber", "🥒");
        ICONS.put("خیار", "🥒");
        ICONS.put("carrot", "🥕");
        ICONS.put("هویج", "🥕");
        ICONS.put("mushroom", "🍄");
        ICONS.put("pasta", "🍝");
        ICONS.put("noodle", "🍜");
        ICONS.put("noodles", "🍜");
        ICONS.put("beans", "🫘");
        ICONS.put("lentil", "🫘");
        ICONS.put("lentils", "🫘");
        ICONS.put("عدس", "🫘");
        ICONS.put("spinach", "🥬");
        ICONS.put("اسفناج", "🥬");
        ICONS.put("apple", "🍎");
        ICONS.put("سیب", "🍎");
        ICONS.put("banana", "🍌");
        ICONS.put("موز", "🍌");
        ICONS.put("corn", "🌽");
        ICONS.put("avocado", "🥑");
        ICONS.put("bacon", "🥓");
        ICONS.put("nuts", "🥜");
        ICONS.put("peanut", "🥜");
        ICONS.put("honey", "🍯");
        ICONS.put("عسل", "🍯");
        ICONS.put("yogurt", "🥣");
        ICONS.put("ماست", "🥣");
        ICONS.put("flour", "🌾");
        ICONS.put("water", "💧");
        ICONS.put("آب", "💧");
        ICONS.put("parsley", "🌿");
        ICONS.put("جعفری", "🌿");
        ICONS.put("leek", "🌿");
        ICONS.put("تره", "🌿");
        ICONS.put("fenugreek", "🌿");
        ICONS.put("شنبلیله", "🌿");
        ICONS.put("mint", "🌿");
        ICONS.put("نعنا", "🌿");
        ICONS.put("walnut", "🌰");
        ICONS.put("گردو", "🌰");
        ICONS.put("pomegranate", "🔴");
        ICONS.put("انار", "🔴");
        ICONS.put("barberries", "🔴");
        ICONS.put("زرشک", "🔴");
        ICONS.put("kidney beans", "🫘");
        ICONS.put("لوبیا قرمز", "🫘");
        ICONS.put("رشته", "🍜");
        ICONS.put("آرد", "🌾");
        ICONS.put("کره", "🧈");
        ICONS.put("نمک", "🧂");
        ICONS.put("dill", "🌿");
        ICONS.put("شیوید", "🌿");
        ICONS.put("basil", "🌿");
        ICONS.put("ریحان", "🌿");
        ICONS.put("rum", "🥃");
        ICONS.put("رام", "🥃");
        ICONS.put("tequila", "🌵");
        ICONS.put("تکیلا", "🌵");
        ICONS.put("lime", "🍋");
        ICONS.put("pineapple", "🍍");
        ICONS.put("آناناس", "🍍");
        ICONS.put("coconut milk", "🥥");
        ICONS.put("شیر نارگیل", "🥥");
        ICONS.put("eggplant", "🍆");
        ICONS.put("بادمجان", "🍆");
        ICONS.put("turmeric", "🟡");
        ICONS.put("زردچوبه", "🟡");
        ICONS.put("saffron", "🌼");
        ICONS.put("زعفران", "🌼");
        ICONS.put("cabbage", "🥬");
        ICONS.put("کلم", "🥬");
        ICONS.put("cinnamon", "🟤");
        ICONS.put("دارچین", "🟤");
        ICONS.put("chickpeas", "🫛");
        ICONS.put("نخود", "🫛");
        ICONS.put("tahini", "🫙");
        ICONS.put("ارده", "🫙");
        ICONS.put("tamarind", "🟤");
        ICONS.put("تمبر هندی", "🟤");
        ICONS.put("dried lime", "🍋");
        ICONS.put("لیمو عمانی", "🍋");
        ICONS.put("celery", "🥬");
        ICONS.put("کرفس", "🥬");
        ICONS.put("raisins", "🍇");
        ICONS.put("کشمش", "🍇");
        ICONS.put("rosewater", "🌹");
        ICONS.put("گلاب", "🌹");
        ICONS.put("vanilla", "🌸");
        ICONS.put("وانیل", "🌸");
        ICONS.put("chocolate", "🍫");
        ICONS.put("شکلات", "🍫");
        ICONS.put("cocoa powder", "🍫");
        ICONS.put("پودر کاکائو", "🍫");
        ICONS.put("salmon", "🐟");
        ICONS.put("ماهی سالمون", "🐟");
        ICONS.put("dried plums", "🟣");
        ICONS.put("آلو", "🟣");
        ICONS.put("dried apricot", "🍑");
        ICONS.put("قیسی", "🍑");
        ICONS.put("split peas", "🫛");
        ICONS.put("لپه", "🫛");
        ICONS.put("grape leaves", "🍃");
        ICONS.put("برگ مو", "🍃");
        ICONS.put("oats", "🌾");
        ICONS.put("جو", "🌾");
        ICONS.put("tortilla", "🫓");
        ICONS.put("تورتیلا", "🫓");
        ICONS.put("coffee", "☕");
        ICONS.put("قهوه", "☕");
        ICONS.put("فلفل", "🌶️");
        ICONS.put("روغن", "🫒");
        ICONS.put("زعفرون", "🌼");
        ICONS.put("تخمه", "🌻");
        ICONS.put("sunflower seeds", "🌻");
    }

    public static String iconFor(String ingredient) {
        return ICONS.getOrDefault(ingredient.trim(), DEFAULT_ICON);
    }

    private IngredientIcons() {
    }
}
